V1.17.1
AnacondaRecipes/hatchling-feedstock pull request #3
Opened 2023-08-10 20:52 UTC by SC426

2023-08-10 21:18 UTC, M-Waszkiewicz-Anaconda approved these changes
LGTM

2023-08-10 21:54 UTC, JeanChristopheMorinPerso requested changes

2023-08-10 21:54 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - wheel
`wheel` shouldn't be required. `hatchling` uses its own code to package itself, see https://github.com/pypa/hatch/blob/master/backend/pyproject.toml#L3-L4.

2023-08-10 21:54 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +{% set version = "1.17.1" %}
We might want to update to 1.18.0 since it's the latest version.

2023-08-10 21:54 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - trove-classifiers 2023.3.9
`editables` is missing from the list of requirements, see https://github.com/pypa/hatch/blob/master/backend/pyproject.toml#L37.

2023-08-10 21:54 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - pathspec 0.10.3
In theory, it requires >=0.10.1

2023-08-10 22:37 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:30: missing_wheel: For pypi packages, wheel should be present in the host section
Errors were found

</details>

2023-08-10 22:37 UTC, SC426 commented on recipe/meta.yaml
> +    - pathspec 0.10.3
Just keeping the linter satisfied

2023-08-10 22:39 UTC, SC426 commented on recipe/meta.yaml
> +    - pathspec 0.10.3
0.10.3 is the closest we have

2023-08-11 13:46 UTC, JeanChristopheMorinPerso approved these changes

2023-08-11 13:47 UTC, merged